### ISSUE TITLE
现在trino 对接prometheus 有什么解决方案吗

### ISSUE THREAD

**Issue by lxd5866** [sqlcore/presto-teach#3]
我在做  !(trino-operator )[https://github.com/lxd5866/trino-operator]， 后续希望给 trino 加上监控，希望请教一下这一块有什么比较成熟的方案

**Comment by feloxx** [comment]
差不多有3个大方向把

- javaagent对接presto的jmx，这个对程序有一定的侵入性
- 单独起一个exporter，我之前有做过一个，就是把presto自己暴露的运维接口按照Prometheus的方式转一下格式，https://github.com/feloxx/presto_exporter
- 直接在presto引入Prometheus的包，按照规范重新开发，算是全部重新开发，这个是成本最高的了。

**Comment by feloxx** [comment]
https://github.com/sqlcore/presto-teach/blob/master/08_%E8%BF%90%E7%BB%B4%E4%B8%8E%E7%9B%91%E6%8E%A7/%E5%AF%B9%E6%8E%A5Prometheus%E7%94%9F%E6%80%81.md
